# Required to run your project under the correct environment.
language: php

notifications:
  email: false

# Versions of PHP you want your project run with.
php:
  - 7.1
  - 7.2
  - 7.3

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install

# Commands you want to run that will verify your build.
script:
  - composer validate --no-check-all --strict
  - composer run-script lint
  - mkdir -p ./build/logs/
  - composer run-script test:coverage
after_success:
  - travis_retry php vendor/bin/coveralls -v
  - ./vendor/bin/test-reporter
